### ISSUE TITLE
Redirect to the sign in page when there's no user authentication present

### ISSUE THREAD

**Issue by fermion** [goinvo/staffplan-next-app#1]
Currently the React page tries to load itself regardless of whether there's someone signed into the app or not. Ideally the React could would:

1. Detect that nobody is signed in
2. Redirect to the sign in page (URL based on environment)
  * production: https://staffplan.fermion.dev/sign_in
  * everything else: http://localhost:3000/sign_in

**Comment by HankC138** [comment]
Redirect has been added and tested
