### ISSUE TITLE
1st load of any staffplan, should default to "today" view (unless the timeline is shifted to somewhere I was just looking at)

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#102]
Today view = left-most weeks shown are 1 week in the past, the current week (week of 2.Sep), and future weeks... right now, the timeline is defaulting to 2nd week in July.
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/4e108d26-0f2d-41f0-898c-28ce9926ed44">

**Comment by zhukovdigital** [comment]
@jsonin and whats behaviour should be on clicking arrow btn in the header? Which date range, next three months from today?

**Comment by jsonin** [comment]
If I click the forward arrow button, assuming we're using the image in the 1st message as the reference, the timeline should switch forward to the next week in the sequence, in this case, W1 Oct.

This should be the default timeline setting, when I click on "Today"... where I can see one week in the past, this week, and the rest of the cells are the future. Screenshot attached:
<img width="848" alt="image" src="https://github.com/user-attachments/assets/d5b8c53a-21b1-4612-a61d-c2ba7448e5ad">
