### ISSUE TITLE
Can't edit 2nd week of any view

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#103]
I cant edit the 2 weeks located on the left-hand side of the current timeline
<img width="174" alt="image" src="https://github.com/user-attachments/assets/9edf493b-d96b-4018-8849-be0579bf8929">

**Comment by zhukovdigital** [comment]
@jsonin , what logic should be used to disable the input fields? if the project dates (Start date, End date) do not match the dates in the grid, then we disable them, correct?

**Comment by jsonin** [comment]
The start and end dates are for calculations and verbal awareness... the start/end aren't hard functions to set when people can input hours.

I don't think planned and actual inputs should be restricted.

Make sense?

**Comment by zhukovdigital** [comment]
> The start and end dates are for calculations and verbal awareness... the start/end aren't hard functions to set when people can input hours.
> 
> I don't think planned and actual inputs should be restricted.
> 
> Make sense?

Sure, will fixed
