### ISSUE TITLE
Fill Forward only filling current week, needs to fill all visible weeks in the future

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#105]
<img width="47" alt="image" src="https://github.com/user-attachments/assets/22310cd7-73f1-409f-87b0-4966c9ef5cf1">

**Comment by jsonin** [comment]
Yes, exactly.Press arrow -> populates all visible inputs (with 0 or whatever number you put in).On Sep 6, 2024, at 2:35 PM, Oleksandr Zhukov ***@***.***> wrote:﻿
@jsonin clicking this btn with arrow should populate all visible inputs throw the row?

**Comment by jsonin** [comment]
nice-to-have: if there is a project end date, fill to the end of the project.
[note: we'll need to have some common/knowable behavior to the fill-forward, and this changes the behavior].
TBD

**Comment by zhukovdigital** [comment]
@jsonin I think we can use the same logic with estimated weekly hours when we adding a person to a project and set the weekly hours for assignment, what do you think about it?

**Comment by jsonin** [comment]
So I get the idea... the fill forward adjusts to the end-of-the-project, if someone set the week the project ends?

**Comment by zhukovdigital** [comment]
> So I get the idea... the fill forward adjusts to the end-of-the-project, if someone set the week the project ends?

Yup, I think it`s rather logically.

**Comment by jsonin** [comment]
That works.
If there is a pre-set "end of project" date, the fill fills up to that end date.
If there is no pre-set "end of project" date, the fill only fills up the visible weeks in the current screen.
Cool

**Comment by jsonin** [comment]
BTW, Fill is a higher priority issue... since it's also acting like a lite-delete (if you were to use 0s)...

**Comment by zhukovdigital** [comment]
> BTW, Fill is a higher priority issue... since it's also acting like a lite-delete (if you were to use 0s)...

Got it, It will be the first task I work on.
