### ISSUE TITLE
Green bars not showing up

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#107]
Week 3 should have 46 hours in the total staffplan graph bar (in green + since nobody has put in actuals yet)
<img width="817" alt="image" src="https://github.com/user-attachments/assets/0a6ff82a-85c8-418e-95ec-aa89a96c99bb">

**Comment by zhukovdigital** [comment]
@jsonin , Can u, please more detailed tell me, how correctly we should show total staffplan graph? Should it be green if it week in the past?  We should show only total actual hours if they presents in the week? If actual hours are not present in the week - we should show Proposed/Signed hours? And what about the case when we have on one project of the week only proposed/signed hours and no actuals and on another project, we have actuals and Proposed?

**Comment by jsonin** [comment]
﻿
Bar behavior, simple (for now):If I have no actual hours for a this or a previous week, and I have planned hours, show the green bar.If I have entered any actual hours, show only the grey bar (actual hours only)For future weeks, every week after the current week, show only the green bar (proposed/signed hours).Proposed hours are the light green color, signed hours are the dark green color.…If we wanted a fancier version of graph bar behavior for later: On this week or the previous weeks, show grey and green bars, if I have entered actual hours but haven’t “reached” my planned number yet. More on this later.On Sep 6, 2024, at 2:00 PM, Oleksandr Zhukov ***@***.***> wrote:﻿
@jsonin , Can u, please more detailed tell me, how correctly we should show total staffplan graph? Should it be green if it week in the past?  We should show only total actual hours if they presents in the week? If actual hours are not present in the week - we should show Proposed/Signed hours? And what about the case when we have on one project of the week only proposed/signed hours and no actuals and on another project, we have actuals and Proposed?

**Comment by zhukovdigital** [comment]
@jsonin Got it and it`s already done with it, but need clarification for the bars in the row.
Should we use the same logic? 
![photo_2024-09-11_12-36-26](https://github.com/user-attachments/assets/05e7a04b-ce4b-41ef-a546-adcaea9334c1)
![photo_2024-09-11_12-37-13](https://github.com/user-attachments/assets/b0dc376a-b803-4cff-a53a-18c1b0fdd7bb)

**Comment by jsonin** [comment]
Yes, the future is green (2 colors of green, like you have it).
Anything in the past = Grey... on top timeline AND in the individual project and person rows.
