### ISSUE TITLE
Need to be able to edit OUTSIDE of the project start/stop dates

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#108]
<img width="817" alt="image" src="https://github.com/user-attachments/assets/827c6d73-47d6-4a00-91e2-bdd3085c620c">

**Comment by zhukovdigital** [comment]
https://github.com/goinvo/staffplan-next-app/issues/113 
if we will add this functionality, is it ok to manage dates of the project?

**Comment by jsonin** [comment]
Let's disable the start-end date restriction, and only use that information for a visual mark and seeing when the project should end.

That might be a new feature to have... if the project has start and end dates, highlight the two input boxes at that week.
This is LOW priority.
