### ISSUE TITLE
Add People not working (on Project)

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#109]
<img width="149" alt="image" src="https://github.com/user-attachments/assets/67ad9ae5-4f3d-4495-a837-e5b20ed1f700">

**Comment by zhukovdigital** [comment]
@jsonin should we used present modal for adding person when we click on header " + People" btn?

**Comment by zhukovdigital** [comment]
@jsonin or just adding it inline 
![photo_2024-09-06_16-01-00](https://github.com/user-attachments/assets/79ff899d-d147-4da5-8718-6c0ad64510dc)
And this input should be like autocomplete whith present people and TBD?

**Comment by jsonin** [comment]
When you click on + People, on a particular project staffplan, that new person row (and corresponding open person field) should appear... so the row appears (like in your screenshot). Then I can pick someone who is in our company.

For now, we are catering to small companies, so a pick list/type ahead is fine.

**Comment by zhukovdigital** [comment]
![image](https://github.com/user-attachments/assets/7562e30f-2eb9-46eb-91af-fbc870301994)
I need some clarification for correctly behaviour. So, we click on the + People btn -> Show the last row of the table on the screen, in which we have select input, where we can select the user from the present user list, when user select someone it should be like a regular row in the table, correct? And what should be if user doesn`t select anyone from the users list and start to enter new user, we should create a new user?

**Comment by jsonin** [comment]
Oooh, you basically have it right there with TBD.
Let's add that TBD row, with the 2 input rows... that looks good.
Then people can assign the person through that TBD dropdown menu.
Does that work?

**Comment by zhukovdigital** [comment]
@jsonin yup, will do it
and what about the behaviour of the input below "Add Person"?

**Comment by jsonin** [comment]
I wonder... do we use TEMPORARILY use the TBD row as the "add new"... but we have the label not be TBD but "Add Person"?

**Comment by zhukovdigital** [comment]
@jsonin, will work on it and then will show you here for confirmation.

**Comment by jsonin** [comment]
Is the "+ People" spawning the TBD _and_ the Add Person input box?
As long as someone clicks the +People, and a single new row appears = good.

Having TBD and an open field = not quite right.
1) Click "+People"
2a) one option: just have the TBD full row appear.... that then allows me to switch TBD to a person in the org (with a drop-down menu)
or
2b) show the Add Person open input box _and_ the proposed hours input boxes too, then I can look-up the person..

**Comment by zhukovdigital** [comment]
@jsonin clicked on the +People => show last row on the video, is it correct variant?
https://github.com/user-attachments/assets/6f705ef6-a305-4554-a482-833595bef527

**Comment by jsonin** [comment]
That's spot on. TY!
