### ISSUE TITLE
Needs empty project row on the bottom of every person's staffplan (for immediate input/typing)

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#110]
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/d1b02f38-ca3e-457c-9e44-eb7dddec2671">

**Comment by zhukovdigital** [comment]
@jsonin , how we will choice the client?

**Comment by jsonin** [comment]
How about an open text box (like the New Project pop-up)?On Sep 6, 2024, at 2:33 PM, Oleksandr Zhukov ***@***.***> wrote:﻿
@jsonin , how we will choice the client?

**Comment by zhukovdigital** [comment]
> How about an open text box (like the New Project pop-up)?On Sep 6, 2024, at 2:33 PM, Oleksandr Zhukov ***@***.***> wrote:﻿ @jsonin , how we will choice the client? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

We need one input in the row, when we will enter the project name, and then we will open a pop-up when the user should the choice client, correctly?

**Comment by zhukovdigital** [comment]
> How about an open text box (like the New Project pop-up)?On Sep 6, 2024, at 2:33 PM, Oleksandr Zhukov ***@***.***> wrote:﻿ @jsonin , how we will choice the client? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

so, we need two inputs 1st. with clients, 2nd with project name, ho we will manage the form control? maybe we need a some btn?

**Comment by jsonin** [comment]
Yes, let’s do that.-JOn Sep 6, 2024, at 3:20 PM, Oleksandr Zhukov ***@***.***> wrote:﻿

How about an open text box (like the New Project pop-up)?On Sep 6, 2024, at 2:33 PM, Oleksandr Zhukov @.> wrote:﻿ @jsonin , how we will choice the client? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: @.>

We need one input in the row, when we will enter the project name, and then we will open a pop-up when the user should the choice client, correctly?
