### ISSUE TITLE
Project details should be available across the service (anytime the project is shown, lemme change "unconfirmed", archive, etc)

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#113]
<img width="340" alt="image" src="https://github.com/user-attachments/assets/f64331ed-86e4-4de2-92cc-93fc6ec41b22">

Right now, this is only available at the project roll-up.
Gimme at my staffplan + Project.

**Comment by zhukovdigital** [comment]
@jsonin should we use status of assignment FOR USER(not for whole project) when we change the status (archive/confirmed/unconfirmed)?

**Comment by jsonin** [comment]
There are 2 statuses here.
Confirmed/Unconfirmed is a status of the project... has it been signed by us and another company with a Statement of Work (ie a legal framework to work against).
Confirmed/Unconfirmed = project + person-wide.
We haven't yet implemented how the UI and experience changes when the project goes from unconfirmed to confirmed. That's later, but we're capturing the idea now.

Then there is Proposed/Planned, which is set per person on the project team.
Someone may propose to be on the project, but the project leader should "ok" it. It's a mini agreement between the project team.

**Comment by HankC138** [comment]
@jsonin 
<img width="295" alt="image" src="https://github.com/user-attachments/assets/f1899d6d-9bf6-4049-b130-f08711fa8bdb">
would you like the elipsis menu to be how it's displayed on myStaffplan? so the project can be edited? currently in a single project view you have the project details at the top of the screen, in the all projects view you have the elipsis menu, it would probably make most sense to just do the elipsis menu again for mystaffplan as the layout is similar to all projects.
