### ISSUE TITLE
Confirmed Project: not propagating 

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#116]
Clicked to confirm project, but my plan isn't confirmed.
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/dc3ca54b-4d77-4d18-b0e6-470ebfc49a6e">

Future functionality: confirmed can be a status for each person on a project ("Yes, as the project lead, X Person has been confirmed on this project, and Y Person is not confirmed).

**Comment by zhukovdigital** [comment]
@jsonin It seems like we have already functionality for each person assignment status on the project, cause of it I think you can`t change the status on the MyStaffplan from the project page, when u change the status there.

**Comment by jsonin** [comment]
I can't find a place in the UI to change each person's assignment status... other than on the project list screen with the ellipsis modal dialog box. I've tried switching that on and off... and it doesn't work.

What if we had the "Proposed" in the above screenshot, be a toggle... a link (since it already has the blue line underneath)... to go from Proposed to Planned... and then back again if needed.

Then we can delete "unconfirmed assignment" labels across the service.
?

**Comment by zhukovdigital** [comment]
@jsonin So, just clicking on status (For example Proposed will change the status to Signed and vice versa? Got it, will do

**Comment by jsonin** [comment]
@zhukovdigital Yup, that works. Thank you!
