### ISSUE TITLE
Bars not dynamically moving when data is inputted into individual cells

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#119]
<img width="360" alt="image" src="https://github.com/user-attachments/assets/378512a5-8d69-4b83-bc28-be913381134e">

**Comment by zhukovdigital** [comment]
@jsonin It should works for now, can close this issue?

**Comment by jsonin** [comment]
Yes, it does work, as I click on a different cell (after inputting the hours).
So this bug is complete.

I may open a new Feature to animate the bar (a 250ms up or down animation) that occurs as I'm typing the number.
