### ISSUE TITLE
Users can edit project details (timing, FTE, name, associated client, and client name)

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#12]

**Comment by HankC138** [comment]
![image](https://github.com/goinvo/staffplan-next-app/assets/114195647/0b66c0e3-d834-4243-92ee-88a34c59ad53)
![image](https://github.com/goinvo/staffplan-next-app/assets/114195647/b06c9595-913c-4d19-88b2-7d286a196260)

a project can be edited in two places
