### ISSUE TITLE
Bars not rendering proposed and actuals together

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#120]
<img width="360" alt="image" src="https://github.com/user-attachments/assets/d557728b-61a9-4dc0-8ce3-0cb421b334af">

**Comment by zhukovdigital** [comment]
@jen-p Can you please clear the cache and try to reproduce it? Cause I try to reproduce it on my side locally nearest twenty times and didn`t met this problem.

**Comment by zhukovdigital** [comment]
@jsonin In which way we should display proposed and actual hours together? Only for current week? In this issue https://github.com/goinvo/staffplan-next-app/issues/107 we discussed it, and you tell that if we have entered any actual hours, we should display it only. So, can you explain more detailed?

**Comment by jsonin** [comment]
I think it's been cleared up (ie working as intended).
