### ISSUE TITLE
Adding a project, adding a person to a project: screen needs to redraw as I add. No hard refresh should be required.

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#123]
If I add a person to a project, the project screen should draw in the new person immediately. No hard refresh needed.

**Comment by zhukovdigital** [comment]
@jsonin do we need to delete the loader spinner when we open a modal with adding a person and then when we saved the person in this modal? 
It should works like: click add person in ellipsis menu => open modal(without loader and changing url) => Save btn => (without loader spinner and cnanging url) => result in the project page.

**Comment by jsonin** [comment]
Ooooh! You already fixed the project +People... by having the person load right there on the project screen. That's great.

To your comment... that works, and it's a lower priority issue, if you want to work on something else.

PS: This is looking good
<img width="336" alt="image" src="https://github.com/user-attachments/assets/14c57490-bc49-4771-990e-baf8db895d5e">
