### ISSUE TITLE
Highlighting particular weeks: Current Week, 1st week in the Project, Last week in the project

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#126]
Desired screen design for highlighting a project current week:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/d13b30b0-9106-45aa-85bc-79efeef48962">

If we know (ie someone has put in start and end dates in the project meta data), then we can highlight the starting week and ending week). Let's use a different color [TBD @jsonin to determine].

**Comment by zhukovdigital** [comment]
@jsonin which colour should be highlight end and start dates?

**Comment by dreeves4321** [comment]
We will define some styling for this, and define where it is displayed, and get back shortly.

**Comment by HankC138** [comment]
<img width="594" alt="image" src="https://github.com/user-attachments/assets/13808c9a-cbbb-4266-995b-edbe79908eb7">
as a temporary solution discussed with @jsonin

**Comment by dreeves4321** [comment]
That’s a good temp solution for single project page. We will need a solution for the assignment rows on people pages and on the all projects page as well, where that info is even more important as it’s not available via the edit project click. On Oct 24, 2024, at 1:14 PM, Corbin Campbell ***@***.***> wrote:﻿
image.png (view on web)
as a temporary solution discussed with @jsonin

**Comment by zhukovdigital** [comment]
@jsonin @HankC138 @dreeves4321 Also on the single project page we have assignment for each user, these assignments can also have ends/start date and it can be different from project start/end date.

**Comment by zhukovdigital** [comment]
Maybe just adding on the header START/END titles and highlight just this row with columns? It would be marks for project start/end date, but for other rows with user assignments we need something else?

**Comment by dreeves4321** [comment]
The assignment end start are not important for now to the user. We’ll revisit that later. Adding more end/start for different meaning will be confusing. Jen got a start on a broader solution for project dates and will finish next week. On Oct 25, 2024, at 5:06 AM, Oleksandr Zhukov ***@***.***> wrote:﻿
Maybe just adding on the header START/END titles and highlight just this row with columns? It would be marks for project start/end date, but for other rows with user assignments we need something else?
