### ISSUE TITLE
Users can edit a person's details (name, email)

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#13]

**Comment by fermion** [comment]
@jen-p I'm going to suggest that we don't actually allow this.

Strong opinion, lightly held: the only person who should be able to update an e-mail address should be the user. Changing someone's e-mail address in a system that doesn't use passwords (but should probably use 2FA eventually) means you're effectively handing control of the account to a bad actor. If an admin's email address was compromised, the entire account would be at risk of something like this from a bad actor.

Same thing for the name — at least the name that we show now. Currently there's a `full_name` field tied to user records. Changing that changes it _everywhere_, so changing @ericbenwa's name in StaffPlan to "Captain Poopy Pants" changes the name displayed across all StaffPlan accounts that @ericbenwa might have access to. If we allow admins to do this, we should build in a way to specify account-specific names (similar to how Discord lets you customize your handle per server). Thoughts?

**Comment by HankC138** [comment]
stale issue will recreate an issue if need be relevant to the modern iteration of staffplan
