### ISSUE TITLE
Faaaaaaar into the Future

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#132]
Looking strange...
<img width="955" alt="image" src="https://github.com/user-attachments/assets/3284c900-618d-4772-8946-8f796706c71f">

**Comment by jsonin** [comment]
And into the past... the allocation goes 10+ time-scrolls into the past (I stopped clicking)...

**Comment by jsonin** [comment]
Ok, I found where this comes from.

Step 1) add person to a project [the 3 dots from the All Projects screen]
<img width="693" alt="image" src="https://github.com/user-attachments/assets/a53de971-c590-4227-ae2f-8b045b3291d7">

Step 2) add "hours/week", any number in that field
Step 3) go to that project and see that the bug exists, since that "add person" function adds time across their entire lifetime!

If you do not enter data into the "hours/week", the StaffPlan acts normally.

<img width="1344" alt="image" src="https://github.com/user-attachments/assets/a168ca07-b704-441f-ac8a-61229ca02c6f">

**Comment by fermion** [comment]
> but then how do we fix the hours assigned by the bug?

Were they persisted? I can pretty easily wipe away the time entered in erroneously once the UI bug is fixed.

**Comment by jsonin** [comment]
Anything that has proposed hours past January 2025 and 
any proposed hours before June 2024....

It should be easy to spot. TY!
