### ISSUE TITLE
Roll-ups, Aggregation needs TLC

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#138]
On the "Projects" roll-up screen:
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/436f8d41-865c-4fc8-97b7-bc76d0a82f0e">

On the individual Project screen:
![image](https://github.com/user-attachments/assets/fe0110fc-2e16-42ab-b723-7ad3fbe75846)

At first I thought it might have to do with the Add Person and hours/week bug, but something else isn't adding up here.

**Comment by zhukovdigital** [comment]
@jsonin  are u about columns in the header? As we discussed earlier in bars adjustments issue, we show only actual hours if any of actual hours is entered?
