### ISSUE TITLE
Adding a project [input box], of a project that already exists... should be added to that person's staffplan

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#147]
If I want to add ANY project to a staffplan, I should be able to type in the name of the project, or type in the name of the client, and then go.

Don't block me from adding a project that already exists to a staffplan.
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/8d600f8d-da84-4fca-afc0-f09a80acb301">

Maybe the UI needs to change there... where 2 input boxes need to be there, without a modal/pop-up (which is annoying).

**Comment by zhukovdigital** [comment]
@jsonin so, I will just add one input with client choose under the project name input?

**Comment by zhukovdigital** [comment]
@jsonin Is it ok to have a btn like this? 
![image](https://github.com/user-attachments/assets/80d2efa6-43f6-4984-b4f3-e7fd98975c0b)

**Comment by jsonin** [comment]
Oooo, this is getting close.
Can "Project Name" and "Client" be on the same line/x axis? 
Does a carriage return save it (vs having an explicit button) and just have implicit save?

**Comment by zhukovdigital** [comment]
@jsonin you want to implement all functionallity on onBlur? without any buttons?

**Comment by jsonin** [comment]
@zhukovdigital ideally, if that doesn't blow up your time, etc.

**Comment by zhukovdigital** [comment]
@jsonin Ok, will try and inform you here.
