### ISSUE TITLE
TBD option when adding people to a project

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#150]
On the actual project page, when I click on +People, one of the options (probably the last option) should be "TBD" for assignments we dont yet know who will do.

<img width="617" alt="image" src="https://github.com/user-attachments/assets/bce37076-135d-4cb7-af08-1f37548d407c">

**Comment by zhukovdigital** [comment]
@jsonin But when we selected this option "TBD" => we r still can change the our choose, correctly?

**Comment by jsonin** [comment]
Yes, we should be able to change that TBD... once a staff decision has been made... to a real person.

**Comment by jsonin** [comment]
btw @HankC138, the Add Person pull-down doesn't actually have all the people who have been invited but only those who have accepted the invite. Mmmmmm....

**Comment by HankC138** [comment]
@fermion do users exist in the DB before they've accepted the invite?

**Comment by fermion** [comment]
@HankC138 yup!

**Comment by HankC138** [comment]
> @HankC138 yup!

And they have a company assigned before accepting as well? I'm just trying to understand why if they are in the database they aren't showing, the invite isn't a concept the front end understands so I'm assuming it's something to do with an association.

**Comment by zhukovdigital** [comment]
@HankC138, @jsonin   I filtered people on the UI, if they already have an assignment on the project => not showing there in the dropdown, cause we can`t select people which already have an assignment on the project. It`s easy to fix, but is it logic to have there in dropdown if we can`t select it?

**Comment by jsonin** [comment]
Yes, if they're already assigned to that project, they dont show up in the list (for that project)

**Comment by fermion** [comment]
> > @HankC138 yup!
> 
> And they have a company assigned before accepting as well? I'm just trying to understand why if they are in the database they aren't showing, the invite isn't a concept the front end understands so I'm assuming it's something to do with an association.

Tested this quickly locally by inviting a new user:

<img width="1840" alt="Screenshot 2024-09-17 at 2 49 27 PM" src="https://github.com/user-attachments/assets/98a54060-0e62-4d0d-bd78-1eec72e4bfdb">

When someone is invited they're instantly added to the company, there's no invitation to accept. We could change that down the road, but tl;dr: adding someone to the account is immediate and immediately incurs a pro-rated cost 👍🏻

**Comment by HankC138** [comment]
https://github.com/user-attachments/assets/8e302d92-1478-4546-ad13-e3f48cf7ebd8

how do we feel about the add person input automatically populating with a TBD label? In actuality when you click on the +people button you are automatically creating a TBD assignment. The way it currently works we would have it always show "Add Person" (essentially not being able to explicitly indicate that the assignment already exists for a TBD user) or have it show "TBD" which would be expressly showing you the truth. 

@jsonin
