### ISSUE TITLE
Comment out "Chat" in top right header (temporary until we have chat)

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#155]
Until we have chat working, let's comment out the icon/feature.
<img width="45" alt="image" src="https://github.com/user-attachments/assets/d5ab22db-740e-4860-9c8e-134a48ce6449">

**Comment by jen-p** [comment]
The chat icon was originally meant to open the feedback form, vs chat. But since we now have a chat link which is redundant, could we retain the feedback form, by using it in place of the Feedback link? (while hiding the icon)

**Comment by jsonin** [comment]
Yup, that works @jen-p .
Move the chat-icon instigated pop-up to be what happens when someone clicks "Feedback" in the header.

**Comment by zhukovdigital** [comment]
@jsonin @jen-p so, at the moment we need to open pop-up with modal form when we clicking "Feedback" and hide the icon with chat, correctly?
