### ISSUE TITLE
Staff can be removed or archived from the staff list, with committed hours remaining in project records

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#16]

**Comment by fermion** [comment]
This backend already works this way. When users are made inactive in a StaffPlan account they're not deleted, and neither are any records that they're associated with (assignments, work weeks, etc.)

The front-end will have to take a user's membership status into consideration 👍

**Comment by HankC138** [comment]
stale issue will recreate an issue if need be relevant to the modern iteration of staffplan
