### ISSUE TITLE
Delete behavior: for projects, for people

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#161]
If I add a project, anywhere in StaffPlan, and it has a unique name, it should immediately appear in the screen I'm on (or if I'm in the All "People" screen, the screen will redraw and load that new project.

If I add a project, anywhere in StaffPlan, and it has a record already (the same name, the same client), I should have the option to either
1) add it to the view I'm in (I'm restoring it if had been archived/deleted)
or
2) not load the previously created project (show that it already exists) but to rename my new project.

If I delete a project (currently the archive button) from an individual's StaffPlan, then the project goes away just from that person's StaffPlan. It is not deleted from anyone else's. I can add it back by adding the same named project again to that StaffPlan.

If I delete a project from the main Project page, the project is archived across everyone's staffplan (but again, the data isn't deleted, it's just that the Project is not shown anymore - its in archive status).

MORE HERE

**Comment by HankC138** [comment]
as discussed with @jsonin relocate archive assignment button to ellipsis menu, and change the archive button in the individual project to a text button.
