### ISSUE TITLE
If we're sticking with Airtable, add an email alert that an airtable feedback msg has come through

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#173]
Send an auto-email to staffplan@goinvo.com if any feedback is added to the AirTable form via the Staffplan feedback form.

I can see this getting ugly quickly.
Also, the plop-up is slow to render... and then has an airtable ad once you submit.

**Comment by jen-p** [comment]
Added email action to feedback form. Not sure how to fix the pop up speed or "ad" (and not sure what is meant by ad, is it just the branding because it's an airtable form?)
