### ISSUE TITLE
May be a duplicate, bug after trying to add a new assignment to a project

### ISSUE THREAD

**Issue by fermion** [goinvo/staffplan-next-app#179]
I clicked the "+ People" button here:

<img width="176" alt="Screenshot 2024-10-03 at 9 22 11 AM" src="https://github.com/user-attachments/assets/cafd288e-12d4-409a-ab16-32deea0072e0">

And immediately saw this error. Now the project won't load:

<img width="1472" alt="Screenshot 2024-10-03 at 9 21 54 AM" src="https://github.com/user-attachments/assets/9c042ac6-265c-454e-bcd0-1bd13e41c8b8">

**Comment by zhukovdigital** [comment]
@fermion will fix
