### ISSUE TITLE
Users can add vacation time to their individual plan

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#18]

**Comment by jsonin** [comment]
Is Vacation just a kind of project?
Is this solved?

**Comment by jen-p** [comment]
For now, it's a kind of project, which is fine. This is a future vision concept (hence why it's labeled as v3 project). Can we hold for now, vs closing? 

In the future vision, we wanted vacation/time off to be categorized a little bit more intelligently, so it 1) doesn't look like someone is overloaded while having time off during an assignment 2) not cut into contracted time on an assignment and 3) make it clear this staff is unavailable for a new assignment over that time if it's a protracted length of time

**Comment by jen-p** [comment]
disregard -- let's close and revisit if it comes back

**Comment by HankC138** [comment]
stale issue will recreate an issue if need be relevant to the modern iteration of staffplan
