### ISSUE TITLE
From settings, now global header URLs go to localhost

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#182]
https://staffplan.com/settings/users/new
... but I see the right ui.staffplan.com directs, but then plops over to localhost.

**Comment by HankC138** [comment]
is this still happening for you? @jsonin  when I try to use any of the navbar links when on the settings page it all works fine for me?

**Comment by jsonin** [comment]
Somehow it remedied... ta-da!
All good.
