### ISSUE TITLE
Person hour rollups should remain green until actuals have been filled.

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#185]
See 2 highlighted weeks. Grey in this bar indicates they are actual hours; in this case, they are not yet actuals as they have not been filled in.

<img width="1733" alt="Screenshot 2024-10-07 at 11 01 38 AM" src="https://github.com/user-attachments/assets/799f4391-04da-4385-b81a-50d8dfdf313a">

**Comment by fermion** [comment]
@jsonin this is what you raised in Discord this morning yeah?
