### ISSUE TITLE
escape keyboard to not save editing a project

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#214]
touch ESC on your keyboard, exit out of
<img width="419" alt="image" src="https://github.com/user-attachments/assets/08da92c8-611f-44e6-8767-93a69b2d9c60">
without saving

**Comment by zhukovdigital** [comment]
@jsonin currently saving of the editing project form works only after clicked on the confirm tiffany color button in the top right corner. Should we use ESC keyboard btn to submit form and exit the form?

**Comment by zhukovdigital** [comment]
![Screenshot 2024-10-11 154217](https://github.com/user-attachments/assets/dc49fddb-7b82-4f61-bf38-5cacf4d7f05f)
what about this location of archive btn?

**Comment by zhukovdigital** [comment]
@jsonin The level of efforts depends on which actually place where we will need to use this logic with esc, with this form it will be easy.

**Comment by jsonin** [comment]
I'll be more clear.

We should have undo everywhere in the service.
I add a person to a project, then undo, and the person is no longer added.
I add hours to a project, then undo, and the hours retreat/disappear.

What's the level of effort to build that into the service, across the service?
Don't start engineering this yet.

**Comment by zhukovdigital** [comment]
@jsonin I am not sure that it would be works good if we will added it everywhere, cause it will be not something like browser behaviour. Theoritically it`s possible, but on practice may be work slow and developing not simple. But in this form it will be work fine and fast.

**Comment by jsonin** [comment]
Undo is a universal no-brainer in software.
It's enormously powerful to everyday work, and under-valued in the making of product.

I'm suggesting we figure out what it would take to implement it across the service, ie the strategy and LOE.... then as we smooth out the current rough edges, we work the global UNDO.

Just something to keep near our brains, but not yet work on.
!
