### ISSUE TITLE
No feedback for adding project from myStaffPlan

### ISSUE THREAD

**Issue by bell-oh** [goinvo/staffplan-next-app#232]
Nothing happens when pressing "Enter" after typing in the name of the project (Staffplan in this case). However, if the project name does not already exist, then the new project will actually get added once I click outside of the input field. If the project name already exists, the project doesn't get added (nothing happens on Enter)
https://github.com/user-attachments/assets/04974308-c587-47c1-b7f8-9d5d92eb2713

**Comment by HankC138** [comment]
@jsonin how would you like this to be handled? If we allow enter to submit on this in addition to the onBlur submission we currently use it'll most likely disrupt enter being usable with anything else. IE if we can hit enter to submit this project name it won't allow you to hit enter to do hours for example or any other input that might be displayed on the same page as this form.

**Comment by ericbenwa** [comment]
Some convo on this happening here.
https://github.com/goinvo/staffplan-next-app/issues/369

So the + project is not exclusive for net new projects... but could also do a search for existing projects for that client.
This would allow people to add themselves to an existing project via that new project functionality.
I think that seems reasonable to allow this.

Closing as this is being discussed elsewhere.

Good idea, thank you @bell-oh
