### ISSUE TITLE
Hours on personal staffplan view and people staffplan view are not consistent

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#238]
The personal staffplan page is correct, not sure where the people page is getting 90 from.

<img width="1517" alt="Screenshot 2024-10-16 at 9 18 58 AM" src="https://github.com/user-attachments/assets/9bf1b811-432c-46cb-940c-2c4ae7e9e65d">
<img width="1580" alt="Screenshot 2024-10-16 at 9 18 50 AM" src="https://github.com/user-attachments/assets/17925cf2-0272-40b9-b7bf-4bb624f7ebfe">

**Comment by jsonin** [comment]
Found it.
Archived project is including hours in the rollup...

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/cf08c806-1c97-4603-9027-77c44ac7ec05">

**Comment by HankC138** [comment]
@jsonin @jen-p are we considering this a problem? It only shows those archived hours in the rollup if show archived project view is toggled on? Should that time be included if you can see archived projects or should time from archived projects be ignored always?

**Comment by jsonin** [comment]
There will be times I want to delete something I put in. It's not part of my life, not part of the project, and just needs to go.

There are times that I will not want to see project plans (individual or the larger, multi-person projects). Those aren't deleted but archived, so I can always find them, but they're not in the current views on individuals or the main project roll-up.

Do we need a split function then?
Delete this mo-fo from existence (yes, we keep it but it only lives in a dark, dank cave never to be seen again - unless undo)
and
Archive, where the plan or project disappears from view
?

In the case Jen brings up, this is a delete, and should not be counted in the rollup.
