### ISSUE TITLE
Users can upload profile images

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#24]

**Comment by fermion** [comment]
@jen-p this is something I was going to add for [users](https://github.com/goinvo/staffplan_redux/issues/71) and [companies](https://github.com/goinvo/staffplan_redux/issues/70) on the Rails side. Were you thinking that the StaffPlan should support profile images too? Or is this possibly a dupe?

**Comment by jen-p** [comment]
Could be considered a dupe! I was just trying to capture the user stories in terms of priority, so this isn't something that is super critical for the first phase, but we can close this one in favor of the other
