### ISSUE TITLE
One user shouldn't be able to hide assignments from another user on the second user's Staffplan page.

### ISSUE THREAD

**Issue by jen-p** [goinvo/staffplan-next-app#242]
In this screenshot, I am not Daniel Reeves. We should hide the icon that currently archives (future: hides) so that I am not able to hide assignments from Daniel.

<img width="1670" alt="Screenshot 2024-10-16 at 4 27 11 PM" src="https://github.com/user-attachments/assets/a0862bbe-0e04-45ec-8281-91d20b6284f6">

**Comment by zhukovdigital** [comment]
@jsonin @jen-p Should owner or admin be able to archive(hide) assignments for other users? And what about editing hours? Should user be able to edit hours for another users(admin/owner should be able, I think)?

**Comment by jen-p** [comment]
I don't foresee a usecase where an admin would absolutely need to be able to hide an assignment for another user.

As for editing hours, I think @jsonin would want it to be open for all (or at least for admins) to do so, but will let him confirm.
