### ISSUE TITLE
Assignments are deleted, rather than archived, and only under certain circumstances

### ISSUE THREAD

**Issue by dreeves4321** [goinvo/staffplan-next-app#249]
Assignments can be deleted. This is an action available on the single project view or single person view. It replaces the archive button on the far right, and requires a new icon (delete rather than archive).

Assignments can be deleted if and only if there are 0 actual hours recorded (plan hours are ok). If there are actual hours recorded, the delete button is not available.

There is no concept of archiving an assignment. However, the "show/hide archived" view option should show and hide archived projects on all pages, including single project and single person views.

**Comment by HankC138** [comment]
@dreeves4321 do we have an idea of what icon we'd like to use for this?
