### ISSUE TITLE
Assignments can be hidden/shown [hold]

### ISSUE THREAD

**Issue by dreeves4321** [goinvo/staffplan-next-app#250]
Assignments can be hidden and shown on your "My Staffplan" page. 
Detailed design work is needed to address questions such as:
- can you hide a project that has future planned hours? 
- how do you hide it? how do you unhide it?
-

**Comment by ericbenwa** [comment]
Hoping to cover this here for My StaffPlan.
https://github.com/goinvo/staffplan-next-app/issues/437

Closing this ticket.
