### ISSUE TITLE
Interactive Markers display at Project Start and End Dates

### ISSUE THREAD

**Issue by dreeves4321** [goinvo/staffplan-next-app#257]
Start and end dates of the project are indicated with markers that are interactive. 
Criteria:
- The user can interact with these markers to change the start and end date.
- The detailed interaction is TBDesigned, but ideally includes drag. Drag has considerations regarding the end of screen. One option is enable dragging to locations on screen AND click for a little popup with week selector. 

Detailed Design:
TBD

**Comment by jsonin** [comment]
@zhukovdigital prototyping 2 markers that can be dragged to other weeks (start and end), that then change the start and/or end = worth trying out.

We'll need the feature.
