### ISSUE TITLE
adjust gutter and labels

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan-next-app#274]
<img width="395" alt="image" src="https://github.com/user-attachments/assets/43f69c87-dc53-4ad1-af0b-971f585582ad">

<img width="719" alt="image" src="https://github.com/user-attachments/assets/d7a4b3c9-db00-4b38-b230-16f1c5176a42">

as discussed with @jsonin align the text in the header with the client names and move the plus sign more to the left so the text aligns. 

and hook up the client name to show all projects for that client when clicked

**Comment by zhukovdigital** [comment]
@HankC138 , @jsonin How it should looks like when we clicked on client name? it should add all projects of the client to the current user? It should be present on mobile and non-mobile view?

**Comment by zhukovdigital** [comment]
And about aligns headers/client names should me move title in the Header (Project, etc to the right) so the text will be aligned? letter under letter?

**Comment by jsonin** [comment]
One could just move the Plus Sign a little to the left, ie make a gutter for the + sign.
?
