### ISSUE TITLE
Have planned hours populate on mobile view

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan-next-app#275]
<img width="426" alt="image" src="https://github.com/user-attachments/assets/917cb21c-2aa5-4724-8ce8-bc66aa0012e4">

like the screenshot attached have the hours input boxes auto populate with the value of planned hours for that assignment.

and remove the archive button from mobile view.

**Comment by zhukovdigital** [comment]
@HankC138, @jsonin We should populate all inputs with prepopulate value? or if we have value from backend - show it?

**Comment by HankC138** [comment]
On the mobile view the estimatedWeeklyHours should populate the input if there is one present.
