### ISSUE TITLE
Horizontal divider missing between clients when archived projects are hidden

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#309]
A horizontal divider should always show between clients/orgs.

No Divider, not showing archived projects
<img width="1258" alt="no-divider" src="https://github.com/user-attachments/assets/a917b3a5-1682-4117-a4a5-be2c2df14222">

With Divider, showing archived projects
<img width="1257" alt="with-divider" src="https://github.com/user-attachments/assets/064f1827-3113-40b3-9e92-3b17f33c0dd5">

**Comment by HankC138** [comment]
@ericbenwa is this still happening for you? When I attempt to recreate this locally or in production I'm unable to make the dividers disappear. Is there something else not shown in the screenshot that might be effecting this outcome?

**Comment by ericbenwa** [comment]
Yes, still happening for me.
Mac Chrome.

I went to view another persons profile and same thing there.
The horiztonal divider is missing between clients.
<img width="1261" alt="Screenshot 2024-11-11 at 10 57 53 AM" src="https://github.com/user-attachments/assets/320a8c8b-368e-4673-aea0-bde2c00339af">

Looking at mine more closely.
Even when Show Archived Projects is ON, not all horizontal dividers between clients exist.
One is missing between Ipsos and MA.gov. But a divider does appear between GoInvo and Ipsos 
<img width="1260" alt="Screenshot 2024-11-11 at 11 01 03 AM" src="https://github.com/user-attachments/assets/83717959-8299-44da-b7dc-0b8a6cdf4f65">
