### ISSUE TITLE
Navigating to sections in the React UI should update the URL so that I can deep link to things

### ISSUE THREAD

**Issue by fermion** [goinvo/staffplan-next-app#32]
# Context

https://github.com/goinvo/staffplan-next-app/assets/2804/b4f7c91e-b27c-464c-b475-a531894e1abf

I should be able to deep link to things in the React UI. From the video above I'm not able to:

* link to my project details
* link to a specific week in time

tl;dr: we should strive to let people deep link to things. This will mean updating the URL/URL parameters such that if I copy/paste the URL to someone else who has access to the StaffPlan account that they should see what I'm seeing.

cc @jsonin for prioritization ❤️

**Comment by HankC138** [comment]
stale issue will recreate an issue if need be relevant to the modern iteration of staffplan
