### ISSUE TITLE
Math problem on projects and project rollup screens

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#343]
![image](https://github.com/user-attachments/assets/568a7192-5fd2-40c0-b6b3-b2d83b9cdda1)
... on the rollup 

but on the individual project screen
![image](https://github.com/user-attachments/assets/96c2c59e-7b2f-47c5-b064-b33646350922)

**Comment by zhukovdigital** [comment]
@jsonin on the rollup should be the same logic? target, plan. actual, delta?

**Comment by jsonin** [comment]
the project rollups (the rollup of all of an organization's projects and the individual project screen) should use everyone who has ever planned and charged against a project. Nobody should be "archived" from the math.

Nobody can be archived from the Project itself, but only from their individual StaffPlan. When I go to a project, I need to see everyone, regardless of status.

Make sense?

**Comment by ericbenwa** [comment]
My guess is that the Projects view, which has the older lingo Planned, Burned, Short, must also have some older calculations.
And the hour math being usead on the individiual project view is the correct one.
Just a hunch.
