### ISSUE TITLE
Current week vertical bar is off by few pixels on People screen

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#355]
Between the weeks and the list of people the background vertical bar is off by few pixels to the right.
Let's line those back up.

<img width="473" alt="pixel off on vertical bar" src="https://github.com/user-attachments/assets/db1b4b16-5372-4889-90e8-d09314f44004">

**Comment by HankC138** [comment]
@ericbenwa are you still seeing this? I'm not seeing it on my end but I'm not aware of a fix going out for it

**Comment by ericbenwa** [comment]
Yes, still seeing on People screen.
![Uploading Screenshot 2024-12-17 at 11.28.58 AM.png…]()
