### ISSUE TITLE
Clicking "Projects" in navbar doesn't work when I'm viewing a client's projects.

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#356]
Reproduce:
Navigate to Projects list.
Click on a client name to see its projects.
Now try clicking on "Projects" in navbar...
it will not navigate to show all clients / all projects... it's stuck on the client I had clicked on earlier on this process.

If I'm viewing a Client, and I click on "Projects" in the navbar, I would expect to go back to seeing all the clients and all the projects.

Also, the url doesn't change to display that client... it still shows as /projects

<img width="796" alt="projects-view" src="https://github.com/user-attachments/assets/5b161840-0228-42c8-a52a-aff68fc81347">

**Comment by zhukovdigital** [comment]
@ericbenwa 
The URL doesn't change because we don't have a client page.
We can create a client page or change the URL ourselves so it looks like this, for example - "/projects?client=GoInvo"
Which option is better to do?

**Comment by jsonin** [comment]
the idea of a client screen, ie /clients/goinvo or /clients/IBM has clear upsides like easier sharing, cleaner, clear representation of a resource... but I get that there are other contexts for a client.

I presume a /projects?client=GoInvo is faster + easier to implement.

What's the level of effort to go /clients/goinvo ?
