### ISSUE TITLE
Revise UI for displaying and hiding archived projects

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#364]
To access archived projects,
display a link at the bottom of the last project in the Projects and MyStaffPlan screen to "Show # archived projects" or "Show archived projects" if can't pull the number.

The list will certainly redraw to display those archived projects in whatever sort has been defined.
That link now changes to "Hide # archived projects", which will do the reverse.

For lack of a better design, we need some visual indicator that a project is Archived... at the moment we can append ` (Archived)`  following the project name (ex `ProjectName (Archived)`). That Archived text is a link to Unarchive project for everyone. There may be a better design we can revise to later.

Showing archived projects on one screen doesn't carry over to showing archived projects in another screen. 

And this is not un-archiving projects, just displaying the archived projects.

If no archived projects exist, don't show the link at the bottom.

Default should be to hide archived projects.
But if someone changes it for a screen (ex. display archived projects), that choice should persist for that session.
So if I navigate away and back to Projects, I see w/e choice I made (hide/show).

The archived project will still have the 3-dot dropdown which will include option for Unarchive Project... (Edit Project, Export CSV, Unarchive Project).

<img width="1483" alt="show-hide-archived-projects" src="https://github.com/user-attachments/assets/4ff67df0-ef55-45b4-8868-e6bf50f4fdde">

**Comment by jsonin** [comment]
What if it was show/hide other projects?
... then that covers hidden and archived.

I think you could still add an archived project to your plan, yes.
But when you're selecting it (or adding the name to the input box), there should be an "(Archived)" note next to the name, so while you're in the process of adding it, StaffPlan tells you in advance that 1) it exists and 2) it's archived.
