### ISSUE TITLE
Revise UI location for adding (+) projects

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#369]
No more `+` pluses everywhere for adding a project.
The `+` is removed from the Client and ClientName text.
The `+` is now being moved to the left of the `Project` column header text.
Only the `+` is clickable to launch the adding of a project.

On click of `+`, let's insert the UI input fields for a new project (maybe quickly animating in) at the top of the list of projects so it's close to where I just clicked (instead of the bottom).
See related ticket: https://github.com/orgs/goinvo/projects/2/views/1?pane=issue&itemId=89735024&issue=goinvo%7Cstaffplan-next-app%7C399

And upon clicking the `+` my focus should be placed inside the Client Name input field so I can quickly type. And then tabbing should bring me to the Project Name input field. And then tabbing out or hitting enter should confirm/solidify that project to feel like the rest of the existing projects.

Note: 
The `+` doesn't currently function on Projects and My StaffPlan.
On My StaffPlan, the new project input fields are displayed by default, we should remove those unless the person clicks the `+`.

<img width="505" alt="add-project" src="https://github.com/user-attachments/assets/bba4fc51-60fa-4bf6-bb89-f920c305b406">

**Comment by jsonin** [comment]
Note how nicely the left-hand grid is too... possible to get that as well?

**Comment by zhukovdigital** [comment]
I would like to clarify a couple of points.

1) Input field for Client should be with autocomplete, but not for Project?
2) If a new client is entered that is not in the autocomplete, should any additional actions be taken?
3) If the input fields are empty and the "Save" button is pressed, should the focus be on the first input field and an error be displayed under the two input fields that they need to be filled in? If one, then focus on it accordingly and display the error?
4) If the project name for the entered client matches an existing project (should the letter case be taken into account or not?), what should I do? Display an error that the project already exists?

Is there any other information I should know?

**Comment by ericbenwa** [comment]
> 1. Input field for Client should be with autocomplete, but not for Project?
I’m ok with autocomplete for Project. This will provide a (reverse) way to add yourself to a project. Good idea!

> 2. If a new client is entered that is not in the autocomplete, should any additional actions be taken?
That new client gets added to the database.

> 3. If the input fields are empty and the "Save" button is pressed, should the focus be on the first input field and an error be displayed under the two input fields that they need to be filled in? If one, then focus on it accordingly and display the error?
- That sounds good.

> 4. If the project name for the entered client matches an existing project (should the letter case be taken into account or not?), what should I do? Display an error that the project already exists?
Letter case should be taken into account (so if the existing project is “StaffPlan”, then me typing “staffplan” into the project name input field should match the existing project “StaffPlan”.
You're making me think of a scenario where I haven't yet entered the `client` input field (so nil), but did add `staffplan` into project name. If I return to client and enter the specific client that has StaffPlan, then those should be match, and not create a duplicate. So the check for duplicates is also run on Save. 
Let me know if that edge case doesn't makes sense.

> Is there any other information I should know?
Some related notes here regarding the + project interaction.
Maybe take a peek at this too as it may be more efficient to work both these issues at the same time.
https://github.com/goinvo/staffplan-next-app/issues/399

**Comment by zhukovdigital** [comment]
It seems illogical to me to add autocomplete for the project input field, since in this case, you can select an existing client and project, and then when saving we will show an error that the project already exists.
It seems appropriate to me to leave autocomplete only for clients.
Because as I understand, the main purpose of this functionality is to add a new project...

**Comment by ericbenwa** [comment]
But why show an error when we could add them to the project?
If they are thinking about the same exact project name within the new project flow, then that likely means they want to work with the existing project (either they already know about it, or might be creating the same one / accidental duplicate project. 

Why not support them to work on an existing project if they're asking for it?

We've had someone try doing this exact thing.
Unknowingly they used this new project flow as a way to add themselves to a project they knew already existed.

So maybe the main purpose, changes to multi-purpose.

- create new client, create new project
- use existing client, create new project
- use existing client, use existing project

![multi-purpose-new-project-flows](https://github.com/user-attachments/assets/a5b1fd11-f5b7-49b0-be3d-736f7b85f959)

**Comment by zhukovdigital** [comment]
I meant the Projects page, where you don't need to add autocomplete to the project input.

Let's go over some of the functionality separately for each page again.
First, the Projects page
1) As I understand it, here we add:
- a new project for an existing client;
- a new client and a new project for him;
2) Therefore, it seems to me that only autocomplete for the client is appropriate here.

MyStaffPlan page

I think that if the client and the project match, we simply add it to my plan.
And I want to clarify what to do in such cases:
1) If the user first starts entering a project, then autocomplete should be shown with all possible projects?
2) If the user selects an existing client, then only projects for this client should be shown in the projects?
3) If a new client is entered, then I don't show any projects in the projects?
And accordingly, the letter case should not be taken into account when checking on two pages?

**Comment by ericbenwa** [comment]
Projects:
Yes, very good point @zhukovdigital on the Projects page!
The autocomplete is only helpful for the client name on the Projects page.

So then have some sort of error message if the person enters an existing project name on the Projects page.
`This project already exists` ... or?

My StaffPlan:
Yes, your notes are all good.

Thank you!

**Comment by zhukovdigital** [comment]
At this moment I display the error under the input field. And I show the message - "Project name already in use".

And another question about the functionality of task 399.
Now, when you click on the client's name (not in the header), an input field appears to add a project, should this option be left?

**Comment by ericbenwa** [comment]
Sounds good.

We can remove the `+` that's to the left of the Client names in each row.
That `+` can now only exist in the column header for `Project`.

The client names in each row should be a link to a filtered Projects view for that client.
So I can see all projects for that client.
Some related info on that view – https://github.com/goinvo/staffplan-next-app/issues/374

Here is the revised full screen view for Projects if helpful.
![projects](https://github.com/user-attachments/assets/2283ada5-80bd-4e6f-bf6e-1cd985de388a)
