### ISSUE TITLE
+ button for adding net new people does not work

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#379]
I may just not be caught up on this.
Maybe because it goes against the billing... and maybe I don't have permission to add people.

1. Is there a way for users to add new people to the org within the app (in addition to the Settings > User Management)?
2. If some users don't have permission to add people, then let's remove the `+` that's paired with People. And the People text will left align.

If we can't inject it nicely into the rest of the app, could we simply make that `+` link people to (assuming they have permission, but if not, don't show the + then)...
https://app.staffplan.com/settings/users/new

<img width="188" alt="Screenshot 2024-12-03 at 10 10 08 AM" src="https://github.com/user-attachments/assets/b5d6a2d5-c026-41c9-ac74-4a282657b9ee">

**Comment by zhukovdigital** [comment]
@ericbenwa 
Currently, new people can only be added via Settings > User Management. The + button currently has no action.

**Comment by ericbenwa** [comment]
Could we link that `+` to this screen for people that have permissions to edit the settings/add users?
https://app.staffplan.com/settings/users

**Comment by zhukovdigital** [comment]
@ericbenwa Yes, we can do it
