### ISSUE TITLE
Project meta data updates

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#380]
On individual project view, some updates on how the project's meta data functions and looks...

1. Handling nil data
- if budget is nil, don't show in read-only view
- if hours is nil, don't show in read-only view
- if start date is nil, don't show in read-only view
- if end date is nil, don't show in read-only view.
<img width="321" alt="Screenshot 2024-12-03 at 10 39 13 AM" src="https://github.com/user-attachments/assets/ed8944b6-5c10-42c9-885f-c09d0b14aaf4">
  
2. In edit, seeing a project with start and end dates, but it is not displaying them in read-only view. However, I then added hours to the project meta data and hit "Done" and it then fixed that issue... displaying the start/end dates in the read-only view. Noticing this must be related to the default dates we provide. Let's remove the default start and end dates StaffPlan gives. A new project will have no dates associated with it unless the user adds those.
<img width="980" alt="Screenshot 2024-12-03 at 10 38 52 AM" src="https://github.com/user-attachments/assets/13ff95e7-8547-48a6-aa8d-10f17e411aec">
  
3. Placeholder text for start/end dates input fields says `dd.LLL.yy`... should it be `dd.Mon.yy`... ?
<img width="177" alt="placeholder-date-text-" src="https://github.com/user-attachments/assets/105a23e5-8055-4774-a448-4f02074a4fff">
  
4. Once I've added start/end dates, I'm unable to remove them and hit "Done". I should be able to remove the dates from a project.
<img width="358" alt="all-dates" src="https://github.com/user-attachments/assets/65026427-5835-4fb7-8288-8933e55b6559">
  
5. Is there a requirement that if I have one date, I must have the other date entered as well? We should allow one date setups. Then in those scenarios the read-only view should display like (`Starts 03.Dec.24`, or `Ends 03.Mar.25`, and if we have both then the current format being used remains the same `03.Dec.25 - 03.Mar.25`)
<img width="358" alt="all-dates" src="https://github.com/user-attachments/assets/65026427-5835-4fb7-8288-8933e55b6559">
  
6. What's the status with Budget input field not working? If we're not ready for that for a bit, can we either remove or make it very obviously disabled looking?
  
7. Can we make the horizontal line between the input fields and the buttons much much lighter? Maybe 70% opacity? Looking for it to be subtle and blend into the background.
<img width="361" alt="horizontal line" src="https://github.com/user-attachments/assets/d26285d9-8ad5-4921-8b33-f8f6d081aca7">

8. Let's remove the (target) hours from the read-only view underneath the project name (see screenshot). Since we're already displaying on the far-right those hours in the total project hours summary, i think we can get away with it... and not duplicate data shown on screen
![Image](https://github.com/user-attachments/assets/41788ad4-99e8-4b99-9665-b6567cf0c16d)

**Comment by HankC138** [comment]
@fermion when I am attempting to remove a start or an end date from a project I am seemingly unable to do so. I tried in graphiql as well. I assume once one has been set there's no way for the backend to remove one? Would that be something we could do and if so what would the recommended way of doing it?

**Comment by fermion** [comment]
@HankC138 start/end dates are on Assignments, is that the field that you're trying to update?

**Comment by HankC138** [comment]
> @HankC138 start/end dates are on Assignments, is that the field that you're trying to update?

no I'm trying to update the startsOn and endsOn dates on the project

**Comment by fermion** [comment]
> > @HankC138 start/end dates are on Assignments, is that the field that you're trying to update?
> 
> no I'm trying to update the startsOn and endsOn dates on the project

Ahh got it — it's because you're trying to set that value to `nil` and setting of that value is skipped if the value passed is...`nil` 😆 🤦🏻 

I may have to refactor this a bit to use input objects to properly support this since what's there is more of a half way solution. If the input format needs to change at all for this I'll let you know, but I'll fix this on the back end.

**Comment by zhukovdigital** [comment]
@fermion Still can't set fields startsOn and endsOn with nil values dates on the project

**Comment by fermion** [comment]
> @fermion Still can't set fields startsOn and endsOn with nil values dates on the project

@zhukovdigital planning to work on this tomorrow 👍
