### ISSUE TITLE
Consistent 3 dot icon, use more subtle one

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#387]
Seeing a few different styles.
My StaffPlan and Projects.

Let's make them all consistent... and use the one from the Projects screen (thinner one) as the one going forward.

<img width="361" alt="skinny-dots" src="https://github.com/user-attachments/assets/8719318b-4db4-44c6-aa0d-fe75fdedf7f2">
<img width="266" alt="fatter-dots" src="https://github.com/user-attachments/assets/5c6bef76-74b9-4415-b85e-ca3a09f6a1f7">

**Comment by zhukovdigital** [comment]
Styles from which picture to apply?
On the right image, the initial color is black, and when you hover it is gray.
On the left image, the initial color is less dark and does not change on hover.

**Comment by ericbenwa** [comment]
Let's use the 3-dot icon that's displayed on the Projects screen.

And use that throughout the service (because other screens have a slightly different version [color and size differs]).
- Fix My StaffPlan 3-dot icon
- Fix Individual Project 3-dot icon (that's displayed next to a people)
