### ISSUE TITLE
Add few keyboard shortcuts to navigate

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#434]
`m` = navigates to My Staffplan
`p` = navigates to Projects
`n` = opens new project popup

Left arrow = go left on weeks timeline (the past)
Right arrow = go right on weeks timeline (the future)

Any thoughts for People?

Other ideas?
- shortcut to hit the repeating arrow for entering hours horizontally (`r`)? obviously only applies if shown / in focus for proposed/plan hours

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implement keyboard shortcuts for navigation and opening new project popup. 'm' navigates to My Staffplan, 'p' navigates to Projects, 'o' navigates to People, and 'n' opens the new project popup.

You can review changes in this commit: https://github.com/mnmnk43434/goinvo-staffplan-next-app-434/commit/9559e24d7d176cc76f51ac44b8005a49ce622bca.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ericbenwa** [comment]
@zhukovdigital Sure, let's try it!
