### ISSUE TITLE
Standardize on URL paths and general patterns

### ISSUE THREAD

**Issue by fermion** [goinvo/staffplan-next-app#67]
Today the URL for user staffplans looks like this:

`https://staffplan-ui.fermion.dev/people/%7B%22selectedUserId%22%3A%221%22%7D`

It looks like there's some stringified JSON in the URL. Ideally the front end routes would similar to this:

`https://staffplan-ui.fermion.dev/people/1`

Keeping it simple and clear. @HankC138 @MyStarrySpace what do y'all think of this pattern for URLs?

**Comment by HankC138** [comment]
@fermion that was my bad on being new to nextJS I didn't realize we could change it's concept of the pathName to anything we wanted so I was using object keys to determine what version of my views menu to show. Now that I know we can label it whatever we want I've altered the code to reflect exactly what you have in your suggestion on this issue 👍
