### ISSUE TITLE
CSV export of a project

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan-next-app#90]
Download the CSV for a project.
Keep the monthly hours + totals summary in the CSV.

**Comment by zhukovdigital** [comment]
@jsonin is it ok format for csv? 
![photo_2024-09-05_19-15-02](https://github.com/user-attachments/assets/13985337-da98-4838-8d8d-70d426731939)

and i add btn in the project row to download csv, what do u think about it? 
![photo_2024-09-05_19-22-27](https://github.com/user-attachments/assets/56fc3580-2b88-4b79-a389-14b8ab16d15c)

**Comment by jsonin** [comment]
It looks like a good start for the CSV export.

Since we're mostly billing on a monthly basis it would also be helpful to have the hours per person per month on a project.

How about putting the export as a menu item in the 3 dots
.
.
.
by each project?
